apiVersion: sparkoperator.hpe.com/v1beta2
kind: SparkApplication
metadata:
  creationTimestamp: 2024-10-03T04:51:25Z
  generation: 1
  labels:
    hpe-ezua/app: spark
    hpe-ezua/type: app-service-user
    sidecar.istio.io/inject: "false"
  name: spark-submit-s3proxy-20241003045100
  namespace: harshal-5f31cc28
  resourceVersion: "34329791"
  uid: ae585498-b438-4f82-ae17-4a16464137db
spec:
  deps:
    jars:
      - local:///mounts/shared-volume/shared/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar
      - local:///mounts/shared-volume/shared/jars/kafka-clients-2.6.1.jar
      - local:///mounts/shared-volume/shared/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar
      - local:///mounts/shared-volume/shared/jars/commons-pool2-2.11.1.jar
      - local:///mounts/shared-volume/shared/jars/iceberg-spark-runtime-3.5_2.12-1.6.0.jar
  driver:
    coreLimit: "1"
    cores: 1
    labels:
      version: 3.5.1
    memory: 4g
    serviceAccount: hpe-harshal-5f31cc28
    volumeMounts:
      - mountPath: /mounts/shared-volume/shared
        name: shared-volume
      - mountPath: /mnt/shared
        name: shared-volume
      - mountPath: /mnt/user
        name: user-volume
      - mountPath: /opt/mapr/spark/sparkhs-eventlog-storage
        name: sparkhs-eventlog-storage
  executor:
    coreLimit: "1"
    cores: 1
    instances: 1
    labels:
      version: 3.5.1
    memory: 4g
    volumeMounts:
      - mountPath: /mounts/shared-volume/shared
        name: shared-volume
      - mountPath: /mnt/shared
        name: shared-volume
      - mountPath: /mnt/user
        name: user-volume
  image: gcr.io/mapr-252711/spark-py-3.5.1:v3.5.1.0.1
  imagePullPolicy: Always
  imagePullSecrets:
    - imagepull
  mainApplicationFile: local:///mounts/shared-volume/shared/airflow-jobs/Spark_K8s_Consumer_S3iceberg-SchemaEvol.py
  mode: cluster
  restartPolicy:
    type: Never
  sparkConf:
    spark.driver.extraJavaOptions: -Dcom.amazonaws.sdk.disableCertChecking
    spark.eventLog.dir: file:///opt/mapr/spark/sparkhs-eventlog-storage
    spark.eventLog.enabled: "true"
    spark.executor.extraJavaOptions: -Dcom.amazonaws.sdk.disableCertChecking
    spark.executorEnv.SPARK_USER: harshal
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.spark.s3a.EzSparkAWSCredentialProvider
    spark.hadoop.fs.s3a.connection.ssl.enabled: "true"
    spark.hadoop.fs.s3a.endpoint: http://harshaledf-service.ezdata-system.svc.cluster.local:30000
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.kubernetes.driverEnv.SPARK_USER: harshal
    spark.mapr.user.secret: hpe-autotix-generated-secret-opnbup
    spark.mapr.user.secret.autogen: "true"
  sparkVersion: 3.5.1
  type: Python
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: kubeflow-shared-pvc
    - name: user-volume
      persistentVolumeClaim:
        claimName: user-pvc
    - name: sparkhs-eventlog-storage
      persistentVolumeClaim:
        claimName: harshal-5f31cc28-sparkhs-pvc
status:
  applicationState:
    state: COMPLETED
  driverInfo:
    podName: spark-submit-s3proxy-20241003045100-driver
  executionAttempts: 1
  executorState:
    harshalschemaevoldemos3-532d739250b8be57-exec-1: COMPLETED
  sparkApplicationId: spark-f9a8c7fcc0ac481e96070b65500ece7e
  submissionAttempts: 1
  submissionID: 9665d8e2-36e3-4d06-a558-91c0a6a076db
  submissionTime: 2024-10-03T04:52:00Z
  terminationTime: 2024-10-03T04:57:03Z
