apiVersion: v1
kind: Service
metadata:
  name: {{ include "bert-sentiment-app.fullname" . }}
  labels:
    {{- include "bert-sentiment-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # Refers to the named port 'http' in the deployment container
      protocol: TCP
      name: http
  selector:
    {{- include "bert-sentiment-app.selectorLabels" . | nindent 4 }}
